# Generated by Django 2.0.5 on 2018-05-21 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Completion Date')),
                ('graduation', models.CharField(max_length=50, verbose_name='Graduation')),
                ('organization', models.CharField(max_length=100, verbose_name='Organization')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Organization Website')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise_in', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('position', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('website', models.URLField(blank=True, null=True, verbose_name='Company Website')),
            ],
            options={
                'verbose_name': 'Job Experience',
                'verbose_name_plural': 'Job Experiences',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LanguageSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Language Name')),
                ('skill_level', models.CharField(max_length=50, verbose_name='Skill Level')),
            ],
            options={
                'verbose_name': 'Language Skill',
                'verbose_name_plural': 'Language Skills',
            },
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Marital Status',
                'verbose_name_plural': 'Marital Statuses',
            },
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_website', models.URLField(blank=True, null=True, verbose_name='Company Website')),
                ('position', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recruiter',
                'verbose_name_plural': 'Recruiters',
            },
        ),
        migrations.CreateModel(
            name='RecruiterActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talenthut.Recruiter')),
            ],
            options={
                'verbose_name': 'HRecruiter Event',
                'verbose_name_plural': 'Recruiter Events',
                'ordering': ['talent__user__first_name', 'talent__user__last_name', 'talent__id', '-event_time'],
            },
        ),
        migrations.CreateModel(
            name='RecruiterEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, unique=True)),
                ('message', models.CharField(default='', max_length=300)),
                ('icon', models.ImageField(default='', upload_to='static/img/')),
                ('description', models.CharField(default='', max_length=30)),
            ],
            options={
                'verbose_name': 'Recruiter Event',
                'verbose_name_plural': 'Recruiter Events',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='', max_length=10)),
            ],
            options={
                'verbose_name': 'Sex',
                'verbose_name_plural': 'Sexes',
            },
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.FloatField(default=0)),
                ('birthdate', models.DateField(default='1900-01-01')),
                ('mobile', models.CharField(default='', max_length=20)),
                ('qualification', models.CharField(max_length=100, verbose_name='Qualification')),
                ('birthplace', models.CharField(max_length=100, verbose_name='Birth Place')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/talent/img/')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('expertises', models.ManyToManyField(to='talenthut.Expertise')),
                ('marital_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talenthut.MaritalStatus')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talenthut.Sex')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_title', models.CharField(max_length=100, null=True, verbose_name='Skill Title')),
                ('skill_list', models.CharField(max_length=100, null=True, verbose_name='List of Skills')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talenthut.Resume')),
            ],
            options={
                'verbose_name': 'Technical Skill',
                'verbose_name_plural': 'Technical Skills',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='talent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='talenthut.Talent'),
        ),
        migrations.AddField(
            model_name='recruiteractivity',
            name='recruiter_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talenthut.RecruiterEvent'),
        ),
        migrations.AddField(
            model_name='recruiteractivity',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talenthut.Talent'),
        ),
        migrations.AddField(
            model_name='languageskill',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talenthut.Resume'),
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talenthut.Resume'),
        ),
        migrations.AddField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talenthut.Resume'),
        ),
        migrations.AddField(
            model_name='address',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talenthut.Talent'),
        ),
        migrations.AlterUniqueTogether(
            name='recruiteractivity',
            unique_together={('recruiter', 'talent', 'recruiter_event')},
        ),
    ]
