# Generated by Django 2.0.5 on 2018-05-22 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talenthut', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='talenthut.Talent'),
        ),
        migrations.AlterField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='talenthut.Resume'),
        ),
        migrations.AlterField(
            model_name='jobexperience',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_experiences', to='talenthut.Resume'),
        ),
        migrations.AlterField(
            model_name='languageskill',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_skills', to='talenthut.Resume'),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='recruiteractivity',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_activities', to='talenthut.Talent'),
        ),
        migrations.AlterField(
            model_name='sex',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='technicalskill',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_skills', to='talenthut.Resume'),
        ),
    ]
