# Generated by Django 2.0.5 on 2018-05-23 18:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('talenthut', '0002_auto_20180522_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterActivityHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_unchanged', models.BooleanField(default=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talenthut.Recruiter')),
                ('recruiter_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talenthut.RecruiterEvent')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_activity_histories', to='talenthut.Talent')),
            ],
            options={
                'verbose_name': 'Recruiter Activity History',
                'verbose_name_plural': 'Recruiter Activity Histories',
                'ordering': ['talent__user__first_name', 'talent__user__last_name', 'talent__id', '-event_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-start_date'], 'verbose_name': 'Education', 'verbose_name_plural': 'Educations'},
        ),
        migrations.AlterModelOptions(
            name='recruiteractivity',
            options={'ordering': ['talent__user__first_name', 'talent__user__last_name', 'talent__id', '-event_time'], 'verbose_name': 'Recruiter Activity', 'verbose_name_plural': 'Recruiter Activities'},
        ),
        migrations.AddField(
            model_name='recruiteractivity',
            name='is_unchanged',
            field=models.BooleanField(default=True),
        ),
    ]
