# Generated by Django 2.0.5 on 2018-09-29 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talenthut', '0003_auto_20180921_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='company_website',
            field=models.URLField(null=True, verbose_name='Company Website'),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='position',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='birthplace',
            field=models.CharField(max_length=100, null=True, verbose_name='Birth Place'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='marital_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='talenthut.MaritalStatus'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='qualification',
            field=models.CharField(max_length=100, null=True, verbose_name='Qualification'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='sex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='talenthut.Sex'),
        ),
    ]
